<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Lesson;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    //
    // (公社）日本舞踊協会
    Lesson::create([
      'company_id' => 1,
      'lesson_name' => '伝統文化に触れ合おう',
      'lesson_detail' => '日本古来の礼儀・風習・作法、それらの伝統文化や伝統芸能が社会の中でわすれられないために、子どもたちに自分の国の文化を実技を行いながら教えます。たとえば正しい姿勢とあいさつや、曲に合わせての踊り、日本舞踊の実演鑑賞などです。６年生の国語の学習や社会の歴史学習、音楽の昔の音楽などでも幅広く対応可能です。',
      'lesson_type' => '対面',
      'supports_career_edu' => false,
      'japanease' => true,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => true,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => false,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => true,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => true,
      'sdgs_edu' => true, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => false, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/日本舞踊1.jpeg', // 画像のファイルパスを保存します
      'image_path_one' => 'images/日本舞踊1.jpeg', // 画像のファイルパスを保存します
      'image_path_two' => 'images/日本舞踊2.jpg', // 画像のファイルパスを保存します
      'image_path_three' => 'images/日本舞踊3.jpeg', // 画像のファイルパスを保存します
      'image_path_four' => 'images/日本舞踊4.jpeg', // 画像のファイルパスを保存します
      'image_path_five' => 'images/日本舞踊5.jpeg', // 画像のファイルパスを保存します
      'image_path_six' => 'images/日本舞踊6.jpg', // 画像のファイルパスを保存します
      'image_path_seven' => 'images/日本舞踊7.jpeg', // 画像のファイルパスを保存します
      'image_path_eight' => 'images/日本舞踊8.jpg', // 画像のファイルパスを保存します
      'image_path_nine' => 'images/日本舞踊9.jpg', // 画像のファイルパスを保存します
      'image_path_ten' => 'images/日本舞踊10.jpg', // 画像のファイルパスを保存します
      'image_path_eleven' => 'images/日本舞踊11.jpg', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
      
       
            
    ]);
    
     // 宮村山業　図工
    Lesson::create([
       'company_id' => 4,
      'lesson_name' => '木育コーディネーターと行う廃材図工教室',
      'lesson_detail' => '３年図工「くぎうちトントン」４年 「ギコギコトントン」などの木材を使った図工の学習におすすめ♪林業に携わるなかでまだ使えるのに捨ててしまわれる廃材を使って図工の作品をパワーアップさせませんか⁉授業者は木育コーディネーターの資格をもったプロ！普段は林業をされているので林業のお話を聞くことも可能です♪',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false ,
      'math' => false,
      'society' => false,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => true,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => true,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => true,
      'one' =>false,
      'two' => false,
      'three' => true,
      'four' => true,
      'five' => false, 
      'six' => false,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => false, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/林業1.jpg', // 画像のファイルパスを保存します
      'image_path_one' => 'images/林業1.jpg', // 画像のファイルパスを保存します
      'image_path_two' => 'images/林業2.jpg', // 画像のファイルパスを保存します
      'image_path_three' => 'images/林業3.jpg', // 画像のファイルパスを保存します
      'image_path_four' => 'images/林業4.jpeg', // 画像のファイルパスを保存します
      'image_path_five' => 'images/林業5.jpg', // 画像のファイルパスを保存します
      'image_path_six' => 'images/林業6.jpeg', // 画像のファイルパスを保存します
      'image_path_seven' => 'images/林業7.jpg', // 画像のファイルパスを保存します
      'image_path_eight' => 'images/林業8.jpg', // 画像のファイルパスを保存します
      // 'image_path_nine' => 'images/林業9.jpg', // 画像のファイルパスを保存します
      // 'image_path_ten' => 'images/林業10.jpg', // 画像のファイルパスを保存します
      // 'image_path_eleven' => 'images/林業11.jpg', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
      
     
    ]);
    
    // 宮村山業 社会
    Lesson::create([
      'company_id' => 4,
      'lesson_name' => '教科書だけではわからない林業の世界',
      'lesson_detail' => '林業ってどういう仕事をしているの？普段なかなか会うこともできない、話をきくこともできない林業という仕事についての生の声を知ることができます。５年生社会「森林と共に生きる」の発展学習として、林業の世界の話や後継者問題など幅広く答えていただきます！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false ,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => true,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => true,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' =>false,
      'five' => true,
      'six' => false,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
            'image' => 'images/林業3.jpg', // 画像のファイルパスを保存します
      'image_path_one' => 'images/林業1.jpg', // 画像のファイルパスを保存します
      'image_path_two' => 'images/林業2.jpg', // 画像のファイルパスを保存します
      'image_path_three' => 'images/林業3.jpg', // 画像のファイルパスを保存します
      'image_path_four' => 'images/林業4.jpeg', // 画像のファイルパスを保存します
      'image_path_five' => 'images/林業5.jpg', // 画像のファイルパスを保存します
      'image_path_six' => 'images/林業6.jpeg', // 画像のファイルパスを保存します
      'image_path_seven' => 'images/林業7.jpg', // 画像のファイルパスを保存します
      'image_path_eight' => 'images/林業8.jpg', // 画像のファイルパスを保存します
      // 'image_path_nine' => 'images/林業9.jpg', // 画像のファイルパスを保存します
      // 'image_path_ten' => 'images/林業10.jpg', // 画像のファイルパスを保存します
      // 'image_path_eleven' => 'images/林業11.jpg', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    
   // （株）上向き
    Lesson::create([
       'company_id' => 10,
      'lesson_name' => '大豆を使った商品を作った理由',
      'lesson_detail' => '大豆を使ったソイクルは大ヒット商品！！起業家でもあり、今やテレビや雑誌などでも大活躍している白坂さんによる授業です！起業家としてのキャリア教育やSDGs教育教育や食育授業、大豆を使った大ヒット商品「ソイクル」をもとに、３年国語「すがたをかえる大豆」の発展学習としての授業もおススメです♪',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => true,
      'math' => false,
      'society' => false,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => true,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/大豆1.jpg', // 画像のファイルパスを保存します
      'image_path_one' => 'images/大豆1.jpg', // 画像のファイルパスを保存します
      'image_path_two' => 'images/大豆2.jpeg', // 画像のファイルパスを保存します
      'image_path_three' => 'images/大豆3.jpeg', // 画像のファイルパスを保存します
      'image_path_four' => 'images/大豆4.jpg', // 画像のファイルパスを保存します
      'image_path_five' => 'images/大豆5.jpg', // 画像のファイルパスを保存します
      'image_path_six' => 'images/大豆6.jpg', // 画像のファイルパスを保存します
      'image_path_seven' => 'images/大豆7.jpg', // 画像のファイルパスを保存します
      // 'image_path_eight' => 'images/大豆8.jpg', // 画像のファイルパスを保存します
      // 'image_path_nine' => 'images/大豆9.jpg', // 画像のファイルパスを保存します
      // 'image_path_ten' => 'images/大豆10.jpg', // 画像のファイルパスを保存します
      // 'image_path_eleven' => 'images/大豆11.jpg', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
      

    ]);
    
    // 福岡ウイニングスピリッツ
    Lesson::create([
      'company_id' => 2,
      'lesson_name' => '福岡ウイニングスピリッツのバレーボール教室',
      'lesson_detail' => '福岡に初めてプロバレーボールチームが誕生！野球やサッカーと同じように人気のスポーツとなるべく、福岡の子どもたちとの交流を希望しています。体育のソフトバレーやクラブ活動などで選手たちとバレーを教えてもらいながら交流することができます。',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false,
      'math' => false,
      'society' => false,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => true,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => false,
      'special_activities' => false,
      'club_activities' => true,
      'one' =>false,
      'two' => false,
      'three' => true,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' =>false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => true, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => false, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/fukuoka-sprits3.png', // 画像のファイルパスを保存します
      'image_path_one' => 'images/fukuoka-sprits3.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    
    
        // （一社）みっどらいふ共育協会
    Lesson::create([
      'company_id' => 6,
      'lesson_name' => 'あなたの命について考えてみよう',
      'lesson_detail' => '生命の誕生や二次性徴、多様性などから幅広く授業展開可能です。講演、個別相談3000人以上対応の専門家が病院勤務時代の妊娠や出産の話もおりまぜながらお話をします。４年生保健「性教育」（総合２分の１成人式と絡めることも可能）や５年生理科「人のたんじょう」の発展学習でも対応可能です。',
      'lesson_type' => '対面',
      'supports_career_edu' => false,
      'japanease' => false,
      'math' => false,
      'society' => false,
      'science' => true,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => true,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => false,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => true, // ⑮「性の多様性」教育
      'sexual_violence_edu' => true, // ⑯性暴力に関する教育
      'sexuality_edu' => true, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/性教育5.jpg', // 画像のファイルパスを保存します
       'image_path_one' => 'images/性教育5.jpg', // 画像のファイルパスを保存します
      'image_path_two' => 'images/性教育2.jpg', // 画像のファイルパスを保存します
      'image_path_three' => 'images/性教育3.jpg', // 画像のファイルパスを保存します
      'image_path_three' => 'images/性教育1.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    
    
    // FBS福岡    社会、キャリア教育
    Lesson::create([
      'company_id' => 3,
      'lesson_name' => 'テレビ局の仕事をのぞいてみよう',
      'lesson_detail' => '情報局ってどういう仕事をしている？アナウンサー、プロデューサー、カメラマンなど、テレビ局で働く人々について知ることができます。社会「未来とつながる情報」としての授業も可能です。また総合のキャリア教育や防災教育、ネットリテラシー教育など幅広く対応致します。早めの依頼であればアナウンサーが授業をしに行くことも可能です！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => true,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => true,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' => false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => true, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/テレビ局.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
      ]);
    
    // FBS福岡
    Lesson::create([
       'company_id' => 3,
      'lesson_name' => 'テレビ局の情報リテラシーとは？',
      'lesson_detail' => '情報化社会である現代。情報リテラシーは必須スキルとなっています。たくさんの情報を届けてくれるテレビ局の情報リテラシーはどのようになっているのでしょうか？可能時期によってはアナウンサー対応も可能です。また放送局見学も時期により可能です！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false,
      'math' => false,
      'society' => false,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => true,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' => true,
      'two' => true,
      'three' => true,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/ネットリテラシー.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    
    
    
     //（株）つなぐ看護師
    Lesson::create([
     'company_id' => 5,
      'lesson_name' => '看護師業界の方が教える医療現場の世界',
      'lesson_detail' => '長年看護業界に携わっていた方から、お話を聞くことができます。現在は介護タクシーや訪問介護を事業とされているので、自分で起業された経験もふまえて、５年６年「キャリア教育」での授業も可能です。長年の看護師の経験から４年「福祉教育」についての授業もできます。',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false ,
      'math' => false,
      'society' => false,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => true,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/看護師.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    

    
    // ローカルフードサイクリング（株）
    Lesson::create([
      'company_id' => 7,
      'lesson_name' => '捨てない暮らしの先にあるものとは？',
      'lesson_detail' => 'LFCコンポストは大ヒット商品！！SDGs教育の先駆者でもあり、今やテレビや雑誌、行政からも引っ張りだこの平さんによる授業です！「捨てない暮らし」で台所を起点とした食循環をつくるをビジョンに福岡や東京を中心に幅広く事業展開されています！20年以上前から学校などで授業を行われているので幅広く対応可能です！SDGs教育や家庭科の食育授業など授業展開の幅は本当に広いです♪',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false,
      'math' => false,
      'society' => false,
      'science' => true,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => true,
      'physical_education' => true,
      'life_skills' => true,
      'ethics' => false,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>true,
      'two' => true,
      'three' => true,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => true,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/コンポスト.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    
    // アノテーションサポート（株）
    Lesson::create([
      'company_id' => 8,
      'lesson_name' => '世界の子どもたちのことを知ろう',
      'lesson_detail' => '無国籍の子どもをたちを救うべく事業展開を行われています。発展途上国の子どもたちの現状などを実際の生の声で子どもたちに伝えてくれます。６年生社会「地球規模の課題の解決と国際協力」や、起業家でもあるのでキャリア教育などでも授業対応可能です！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => false,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/ユニセフ.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能    
    ]);

// （株）西日本新聞社
    Lesson::create([
      'company_id' => 9,
      'lesson_name' => '新聞を正しく読もう',
      'lesson_detail' => '子どもたちに新聞についてもっと知ってもらいたいという思いから教育現場での新聞活用授業を毎年行われています。新聞記者の仕事についての説明や新聞の作り方の授業も対応可能。５年生社会「未来とつながる情報」の発展学習として授業や国語における「新聞」の読み方の授業、キャリア教育も事前の相談次第では対応可能です！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => true,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/新聞記者.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);


    
    // 立木美江（日本画家）
    Lesson::create([
       'company_id' => 11,
      'lesson_name' => '日本絵画の歴史に触れ、絵を描いてみよう',
      'lesson_detail' => '2023年度福岡銀行のカレンダーにも採択されている立木美江さんによる絵画指導！絵画に欠かせない画材のことについても教えていただけます！普段はアトリエにて絵画教室を開くなど幅広く創作普及活動を行われている立木さんが学校教育においての絵画時の講師をしてくださいます！',
      'lesson_type' => '対面',
      'supports_career_edu' => false,
      'japanease' => false,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => true,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => false,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>true,
      'two' => true,
      'three' => true,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => true,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => false, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/日本画家152243.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能    
    ]);
    
    // （株）フリップザミント
    Lesson::create([
      'company_id' => 12,
      'lesson_name' => '消費者のもとに届くまでの生産者たちの想いを知ろう',
      'lesson_detail' => '「繋がりを可視化し愛のある世界に」をビジョンに生産者から消費者の手に渡るまでの“背景”を大切にしている（株）フリップザミント創業者の久川さんによる授業。ものづくりや生産者との繋がりを大切にしていることから５年家庭科「持続可能な暮らしへ物やお金の使い方」６年家庭科「衣生活を楽しく豊かに」での授業、また農業従事者なので、５年社会「これからの食料生産」での授業も可能です。また起業家としてキャリア教育も可能です！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => true,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => false,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => false,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/農業.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能    
    ]);
    
    // (有)ペーパーカンパニー
    Lesson::create([
     'company_id' => 13,
      'lesson_name' => 'キャッチコピー専門家といっしょにかっこいい見出しを生み出そう',
      'lesson_detail' => 'JR博多シティの名付け親であり、広告キャッチコピーをたくさん輩出している中村さんとの夢の授業！言葉を生み出すことを仕事としているプロなので、国語の言葉などの授業や新聞作りの見出しやテーマ作り、文集の題名など幅広く授業対応可能です！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => true,
      'math' => false,
      'society' => false,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => false,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => true, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/広告.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能      
    ]);
    
    // （株）こたつ
    Lesson::create([
      'company_id' => 14,
      'lesson_name' => '発展途上国の子どもたちのことを知ろう',
      'lesson_detail' => 'テレビや雑誌などでも大活躍！アフリカの孤児・貧困児童と女性へのサポートを目的としたエシカルアパレル「SHIFT 80」代表坂田ミギーさんによる授業です。６年生社会「地球規模の課題の解決と国際協力」での国際理解教育、起業家としてのキャリア教育でも授業可能です！東京在住の為、福岡に帰省時のタイピングでの授業提供となります！',
      'lesson_type' => '対面',
      'supports_career_edu' => true,
      'japanease' => false,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => false,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => false, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/発展途上国.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    
    // 環境活動家・露木志奈
    Lesson::create([
      'company_id' => 15,
      'lesson_name' => '地球温暖化について考えよう',
      'lesson_detail' => '「気候変動を抑えるための講演活動」を日本全国の学校で行っている露木志奈さんによる特別講話。現在は220校３万人と桁は膨れ上がり、日本のグレタさんと言われています。気候変動の影響をもろに受けていくであろう子どもたちをターゲットに「知る機会」を自分が与えようと大学を休学されて挑戦されています。同年代であるからこそ伝わる想いがあります！講話は無料ですが旅費は要相談です！',
      'lesson_type' => '対面',
      'supports_career_edu' => false,
      'japanease' => false,
      'math' => false,
      'society' => true,
      'science' => false,
      'english' => false,
      'music' => false,
      'art_and_crafts' => false,
      'home_economics' => false,
      'physical_education' => false,
      'life_skills' => false,
      'ethics' => false,
      'integrated_studies' => true,
      'special_activities' => false,
      'club_activities' => false,
      'one' =>false,
      'two' => false,
      'three' => false,
      'four' => true,
      'five' => true,
      'six' => true,
      'seven' => false,
      'sdgs_edu' => false, // ①SDGs教育
      'info_edu' => false, // ②情報教育
      'ict_edu' => false,  // ③ICT教育
      'copyright_edu' => false, // ④著作権教育
      'net_literacy_edu' => false, // ⑤ネットリテラシー教育
      'net_moral_edu' => false, // ⑥ネットモラル教育
      'programming_edu' => false, // ⑦プログラミング教育
      'career_edu' => false, // ⑧キャリア教育
      'entrepreneurship_edu' => false, // ⑨起業家精神教育
      'financial_edu' => false, // ⑩金融教育
      'food_edu' => false, // ⑪食育
      'health_edu' => false, // ⑫健康教育
      'disaster_edu' => false, // ⑬防災教育
      'lgbt_edu' => false, // ⑭LGBT教育
      'gender_diversity_edu' => false, // ⑮「性の多様性」教育
      'sexual_violence_edu' => false, // ⑯性暴力に関する教育
      'sexuality_edu' => false, // ⑰性教育
      'cancer_edu' => false, // ⑱癌教育
      'foreign_language_edu' => false, // ⑲外国語教育
      'international_understanding_edu' => false, // ⑳国際理解教育
      'volunteer_edu' => false, // 21ボランティア教育
      'multicultural_coexistence_edu' => false, // 22多文化共生教育
      'peace_edu' => false, // 23平和教育
      'consumer_edu' => false, // 24消費者教育
      'local_edu' => false, // 25郷土教育
      'human_rights_edu' => false, // 26人権教育
      'sovereign_edu' => false, // 27主権者教育
      'school_link_edu' => false, // 28小中連携教育
      'art_edu' => false, // 29芸術教育
      'special_support_edu' => false, // 30特別支援教育
      'universal_design_edu' => false, // 31ユニバーサルデザイン教育
      'inclusive_edu' => false, // 32インクルーシブ教育
      'environment_edu' => false, // 33環境教育
      'safety_edu' => false, // 34安全教育
      'traffic_safety_edu' => false, // 35交通安全教育
      'nature_experience_edu' => false, // 36自然体験教育
      'welfare_edu' => false, // 37福祉教育
      'normative_consciousness_edu' => false, // 38規範意識教育
      'moral_edu' => false, // 39道徳教育
      'mind_edu' => false, // 40心の教育
      'museum_edu' => false, // 41博物館教育
      'animal_protection_edu' => false, // 42動物愛護教育
      'library_use_edu' => false, // 43図書館活用教育
      'nie_edu' => false, // 44ＮＩＥ教育（新聞を学校教育に取り入れる）
      'posting_edu' => false, // 45掲示教育
      'image' => 'images/地球温暖化.png', // 画像のファイルパスを保存します
      'started_date' => '2024-4-14',
      'finished_date' => '2024-3-20',
      'is_reservable' => true,  // 予約可能
    ]);
    }
}
